version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
        sh -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
        - .:/app
        - static_volume:/app/staticfiles
        - media_volume:/app/media
        - ./logs:/app/logs
    ports:
        - "8000:8000"
    environment:
        - DEBUG=True
        - SECRET_KEY=django-insecure-change-in-production
        - DATABASE_URL=postgres://postgres:postgres@db:5432/shop_db
        - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
        db:
          condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
